import { useEffect, useState } from 'react';
import { FaChalkboardTeacher, FaPlus, FaEdit, FaTrash } from 'react-icons/fa';
import { getDepartments } from '../../api/departments';
import { getCoursesByDepartment } from '../../api/courses';
import { createTeacher, deleteTeacher, getTeacherCourses, getTeachers, updateTeacher } from '../../api/teachers';

const BLUE = '#2f73b7';
const empty = { name: '', email: '', phone: '', department_id: '', courseIds: [] };

function TeacherModal({ teacher, departments, onClose, onSaved }) {
  const [form, setForm] = useState(teacher ? { name: teacher.name, email: teacher.email, phone: teacher.phone || '', department_id: teacher.department_id || '', courseIds: [] } : empty);
  const [courses, setCourses] = useState([]); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (!form.department_id) { setCourses([]); return; } getCoursesByDepartment(form.department_id).then(setCourses).catch((e) => setError(e.message)); }, [form.department_id]);
  useEffect(() => { if (teacher) getTeacherCourses(teacher.id).then((items) => setForm((f) => ({ ...f, courseIds: items.map((x) => x.id) }))).catch(() => {}); }, [teacher]);
  const toggle = (id) => setForm((f) => ({ ...f, courseIds: f.courseIds.includes(id) ? f.courseIds.filter((x) => x !== id) : [...f.courseIds, id] }));
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { let result; if (teacher) result = await updateTeacher(teacher.id, form); else result = await createTeacher(form); onSaved(result); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4"><div className="w-full max-w-2xl rounded-2xl bg-white shadow-2xl"><div className="border-b border-slate-200 p-6"><h2 className="text-xl font-bold text-slate-900">{teacher ? 'Edit Teacher' : 'Add Teacher'}</h2><p className="text-sm text-slate-500">A secure temporary login password is generated for new teachers.</p></div><form onSubmit={submit} className="space-y-5 p-6">{error && <div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="grid gap-4 md:grid-cols-2"><Field label="Full name"><input required className="input" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></Field><Field label="Email"><input required type="email" className="input" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></Field><Field label="Phone"><input className="input" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></Field><Field label="Department"><select required className="input" value={form.department_id} onChange={(e) => setForm({ ...form, department_id: e.target.value, courseIds: [] })}><option value="">Select department</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field></div><div><label className="mb-2 block text-sm font-semibold text-slate-700">Courses taught</label><div className="grid gap-2 sm:grid-cols-3">{courses.map((course) => <label key={course.id} className="flex items-center gap-2 rounded-lg border border-slate-200 p-3"><input type="checkbox" checked={form.courseIds.includes(course.id)} onChange={() => toggle(course.id)} /> <span className="text-sm">{course.name}</span></label>)}</div></div><div className="flex justify-end gap-3 border-t pt-5"><button type="button" onClick={onClose} className="rounded-xl bg-slate-100 px-5 py-2.5 font-semibold text-slate-700">Cancel</button><button disabled={saving} className="rounded-xl px-5 py-2.5 font-semibold text-white" style={{ backgroundColor: BLUE }}>{saving ? 'Saving...' : teacher ? 'Save Changes' : 'Create Teacher'}</button></div></form></div></div>;
}
function Field({ label, children }) { return <div><label className="mb-2 block text-sm font-semibold text-slate-700">{label}</label>{children}</div>; }

export default function Teachers() {
  const [teachers, setTeachers] = useState([]); const [departments, setDepartments] = useState([]); const [show, setShow] = useState(false); const [editing, setEditing] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [credentials, setCredentials] = useState(null);
  const load = async () => { setLoading(true); try { const [t, d] = await Promise.all([getTeachers(), getDepartments()]); setTeachers(t); setDepartments(d.filter((x) => ['CS', 'IT', 'IS'].includes(x.name))); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const save = async (result) => { setShow(false); if (result?.temporaryPassword) setCredentials(result.temporaryPassword); await load(); };
  const add = async () => { setEditing(null); setShow(true); };
  const remove = async (id) => { if (!window.confirm('Deactivate this teacher and disable their login?')) return; try { await deleteTeacher(id); await load(); } catch (e) { setError(e.message); } };
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 border-b border-slate-200 pb-5 md:flex-row md:items-center"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl text-white" style={{ backgroundColor: BLUE }}><FaChalkboardTeacher /></div><div><h1 className="text-2xl font-bold text-slate-900">Teacher Management</h1><p className="text-sm text-slate-500">Create teachers and assign their department and courses.</p></div></div><button onClick={add} className="action-primary"><FaPlus /> Add Teacher</button></div>{error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Teacher</th><th className="px-5 py-4">Email</th><th className="px-5 py-4">Department</th><th className="px-5 py-4">Courses</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody>{loading ? <tr><td colSpan="5" className="p-10 text-center text-slate-500">Loading teachers...</td></tr> : teachers.length === 0 ? <tr><td colSpan="5" className="p-10 text-center text-slate-500">No teachers found.</td></tr> : teachers.map((teacher) => <tr key={teacher.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-slate-800">{teacher.name}</td><td className="px-5 py-4 text-slate-600">{teacher.email}</td><td className="px-5 py-4"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold" style={{ color: BLUE }}>{teacher.department_name || 'Unassigned'}</span></td><td className="px-5 py-4 text-slate-600">{teacher.course_count || 0}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={() => { setEditing(teacher); setShow(true); }} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50"><FaEdit /></button><button onClick={() => remove(teacher.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><FaTrash /></button></div></td></tr>)}</tbody></table></div></div>{show && <TeacherModal teacher={editing} departments={departments} onClose={() => setShow(false)} onSaved={save} />}{credentials && <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-900/60 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6"><h2 className="text-xl font-bold">Teacher created</h2><p className="mt-2 text-sm text-slate-600">Temporary password:</p><p className="mt-2 rounded-lg bg-slate-100 p-3 font-mono">{credentials}</p><button onClick={() => setCredentials(null)} className="mt-5 rounded-xl px-5 py-2.5 font-semibold text-white" style={{ backgroundColor: BLUE }}>Done</button></div></div>}</div>;
}
